version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels: [automated]
    open-pull-requests-limit: 5
    groups:
      kubernetes:
        patterns: ["k8s.io/*", "sigs.k8s.io/*"]
      crossplane:
        patterns: ["github.com/crossplane/*"]
      go-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [automated]
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /cluster/images/provider-rabbitmq
    schedule:
      interval: weekly
    labels: [automated]

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    labels: [automated]
