// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PermissionsInitParameters struct {

	// The settings of the permissions. The structure is
	// described below.
	Permissions []PermissionsPermissionsInitParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`
}

type PermissionsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The settings of the permissions. The structure is
	// described below.
	Permissions []PermissionsPermissionsObservation `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The vhost to create the resource in.
	Vhost *string `json:"vhost,omitempty" tf:"vhost,omitempty"`
}

type PermissionsParameters struct {

	// The settings of the permissions. The structure is
	// described below.
	// +kubebuilder:validation:Optional
	Permissions []PermissionsPermissionsParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The vhost to create the resource in.
	// +crossplane:generate:reference:type=github.com/haooliveira84/provider-rabbitmq/apis/cluster/rabbitmq/v1alpha1.Vhost
	// +kubebuilder:validation:Optional
	Vhost *string `json:"vhost,omitempty" tf:"vhost,omitempty"`

	// Reference to a Vhost in rabbitmq to populate vhost.
	// +kubebuilder:validation:Optional
	VhostRef *v2.Reference `json:"vhostRef,omitempty" tf:"-"`

	// Selector for a Vhost in rabbitmq to populate vhost.
	// +kubebuilder:validation:Optional
	VhostSelector *v2.Selector `json:"vhostSelector,omitempty" tf:"-"`
}

type PermissionsPermissionsInitParameters struct {

	// The "configure" ACL.
	Configure *string `json:"configure,omitempty" tf:"configure,omitempty"`

	// The "read" ACL.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// The "write" ACL.
	Write *string `json:"write,omitempty" tf:"write,omitempty"`
}

type PermissionsPermissionsObservation struct {

	// The "configure" ACL.
	Configure *string `json:"configure,omitempty" tf:"configure,omitempty"`

	// The "read" ACL.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// The "write" ACL.
	Write *string `json:"write,omitempty" tf:"write,omitempty"`
}

type PermissionsPermissionsParameters struct {

	// The "configure" ACL.
	// +kubebuilder:validation:Optional
	Configure *string `json:"configure" tf:"configure,omitempty"`

	// The "read" ACL.
	// +kubebuilder:validation:Optional
	Read *string `json:"read" tf:"read,omitempty"`

	// The "write" ACL.
	// +kubebuilder:validation:Optional
	Write *string `json:"write" tf:"write,omitempty"`
}

// PermissionsSpec defines the desired state of Permissions
type PermissionsSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PermissionsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PermissionsInitParameters `json:"initProvider,omitempty"`
}

// PermissionsStatus defines the observed state of Permissions.
type PermissionsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PermissionsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Permissions is the Schema for the Permissionss API. Creates and manages a user's permissions on a RabbitMQ server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rabbitmq}
type Permissions struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	Spec   PermissionsSpec   `json:"spec"`
	Status PermissionsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PermissionsList contains a list of Permissionss
type PermissionsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Permissions `json:"items"`
}

// Repository type metadata.
var (
	Permissions_Kind             = "Permissions"
	Permissions_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Permissions_Kind}.String()
	Permissions_KindAPIVersion   = Permissions_Kind + "." + CRDGroupVersion.String()
	Permissions_GroupVersionKind = CRDGroupVersion.WithKind(Permissions_Kind)
)

func init() {
	SchemeBuilder.Register(&Permissions{}, &PermissionsList{})
}
