name: hashicorp/rabbitmq
resources:
    rabbitmq_resource Resource - terraform-provider-rabbitmq:
        subCategory: ""
        description: The rabbitmq_resource resource implements the standard resource lifecycle but takes no further action. The triggers argument allows specifying an arbitrary set of values that, when changed, will cause the resource to be replaced.
        name: rabbitmq_resource Resource - terraform-provider-rabbitmq
        title: rabbitmq_resource Resource - terraform-provider-rabbitmq
        argumentDocs: {}
        importStatements: []
