apiVersion: rabbitmq.rabbitmq.upbound.io/v1alpha1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    settings:
    - arguments:
        x-queue-type: quorum
      autoDelete: true
      durable: false
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: guest

---

apiVersion: rabbitmq.rabbitmq.upbound.io/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: guest
  name: guest
spec:
  forProvider:
    permissions:
    - configureSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      readSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      writeSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: rabbitmq.rabbitmq.upbound.io/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
