apiVersion: rabbitmq.rabbitmq.upbound.io/v1alpha1
kind: Shovel
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: shovelTest
  name: shoveltest
spec:
  forProvider:
    info:
    - destinationQueue: ${rabbitmq_queue.test.name}
      destinationUri: amqp:///test
      sourceExchange: ${rabbitmq_exchange.test.name}
      sourceExchangeKey: test
      sourceUri: amqp:///test
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: rabbitmq.rabbitmq.upbound.io/v1alpha1
kind: Exchange
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    settings:
    - autoDelete: true
      durable: false
      type: fanout
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: rabbitmq.rabbitmq.upbound.io/v1alpha1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    settings:
    - autoDelete: true
      durable: false
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: rabbitmq.rabbitmq.upbound.io/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
