// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BindingInitParameters struct {

	// Additional key/value arguments for the binding.
	// +mapType=granular
	Arguments map[string]*string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	ArgumentsJSON *string `json:"argumentsJson,omitempty" tf:"arguments_json,omitempty"`

	// The destination queue or exchange.
	Destination *string `json:"destination,omitempty" tf:"destination,omitempty"`

	// The type of destination (queue or exchange).
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// A routing key for the binding.
	RoutingKey *string `json:"routingKey,omitempty" tf:"routing_key,omitempty"`

	// The source exchange.
	// +crossplane:generate:reference:type=github.com/haooliveira84/provider-rabbitmq/apis/namespaced/rabbitmq/v1alpha1.Exchange
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Reference to a Exchange in rabbitmq to populate source.
	// +kubebuilder:validation:Optional
	SourceRef *v2.NamespacedReference `json:"sourceRef,omitempty" tf:"-"`

	// Selector for a Exchange in rabbitmq to populate source.
	// +kubebuilder:validation:Optional
	SourceSelector *v2.NamespacedSelector `json:"sourceSelector,omitempty" tf:"-"`

	// The vhost to create the resource in.
	// +crossplane:generate:reference:type=github.com/haooliveira84/provider-rabbitmq/apis/namespaced/rabbitmq/v1alpha1.Vhost
	Vhost *string `json:"vhost,omitempty" tf:"vhost,omitempty"`

	// Reference to a Vhost in rabbitmq to populate vhost.
	// +kubebuilder:validation:Optional
	VhostRef *v2.NamespacedReference `json:"vhostRef,omitempty" tf:"-"`

	// Selector for a Vhost in rabbitmq to populate vhost.
	// +kubebuilder:validation:Optional
	VhostSelector *v2.NamespacedSelector `json:"vhostSelector,omitempty" tf:"-"`
}

type BindingObservation struct {

	// Additional key/value arguments for the binding.
	// +mapType=granular
	Arguments map[string]*string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	ArgumentsJSON *string `json:"argumentsJson,omitempty" tf:"arguments_json,omitempty"`

	// The destination queue or exchange.
	Destination *string `json:"destination,omitempty" tf:"destination,omitempty"`

	// The type of destination (queue or exchange).
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A unique key to refer to the binding.
	PropertiesKey *string `json:"propertiesKey,omitempty" tf:"properties_key,omitempty"`

	// A routing key for the binding.
	RoutingKey *string `json:"routingKey,omitempty" tf:"routing_key,omitempty"`

	// The source exchange.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The vhost to create the resource in.
	Vhost *string `json:"vhost,omitempty" tf:"vhost,omitempty"`
}

type BindingParameters struct {

	// Additional key/value arguments for the binding.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Arguments map[string]*string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// +kubebuilder:validation:Optional
	ArgumentsJSON *string `json:"argumentsJson,omitempty" tf:"arguments_json,omitempty"`

	// The destination queue or exchange.
	// +kubebuilder:validation:Optional
	Destination *string `json:"destination,omitempty" tf:"destination,omitempty"`

	// The type of destination (queue or exchange).
	// +kubebuilder:validation:Optional
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// A routing key for the binding.
	// +kubebuilder:validation:Optional
	RoutingKey *string `json:"routingKey,omitempty" tf:"routing_key,omitempty"`

	// The source exchange.
	// +crossplane:generate:reference:type=github.com/haooliveira84/provider-rabbitmq/apis/namespaced/rabbitmq/v1alpha1.Exchange
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Reference to a Exchange in rabbitmq to populate source.
	// +kubebuilder:validation:Optional
	SourceRef *v2.NamespacedReference `json:"sourceRef,omitempty" tf:"-"`

	// Selector for a Exchange in rabbitmq to populate source.
	// +kubebuilder:validation:Optional
	SourceSelector *v2.NamespacedSelector `json:"sourceSelector,omitempty" tf:"-"`

	// The vhost to create the resource in.
	// +crossplane:generate:reference:type=github.com/haooliveira84/provider-rabbitmq/apis/namespaced/rabbitmq/v1alpha1.Vhost
	// +kubebuilder:validation:Optional
	Vhost *string `json:"vhost,omitempty" tf:"vhost,omitempty"`

	// Reference to a Vhost in rabbitmq to populate vhost.
	// +kubebuilder:validation:Optional
	VhostRef *v2.NamespacedReference `json:"vhostRef,omitempty" tf:"-"`

	// Selector for a Vhost in rabbitmq to populate vhost.
	// +kubebuilder:validation:Optional
	VhostSelector *v2.NamespacedSelector `json:"vhostSelector,omitempty" tf:"-"`
}

// BindingSpec defines the desired state of Binding
type BindingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BindingInitParameters `json:"initProvider,omitempty"`
}

// BindingStatus defines the observed state of Binding.
type BindingStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Binding is the Schema for the Bindings API. Creates and manages a binding on a RabbitMQ server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rabbitmq}
type Binding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.destination) || (has(self.initProvider) && has(self.initProvider.destination))",message="spec.forProvider.destination is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.destinationType) || (has(self.initProvider) && has(self.initProvider.destinationType))",message="spec.forProvider.destinationType is a required parameter"
	Spec   BindingSpec   `json:"spec"`
	Status BindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BindingList contains a list of Bindings
type BindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Binding `json:"items"`
}

// Repository type metadata.
var (
	Binding_Kind             = "Binding"
	Binding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Binding_Kind}.String()
	Binding_KindAPIVersion   = Binding_Kind + "." + CRDGroupVersion.String()
	Binding_GroupVersionKind = CRDGroupVersion.WithKind(Binding_Kind)
)

func init() {
	SchemeBuilder.Register(&Binding{}, &BindingList{})
}
