// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Binding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Exchange) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FederationUpstream) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OperatorPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Permissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Policy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Queue) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Shovel) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TopicPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vhost) Hub() {}
