// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VhostInitParameters struct {

	// default queue type for new queues
	DefaultQueueType *string `json:"defaultQueueType,omitempty" tf:"default_queue_type,omitempty"`

	// A friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Maximum number of concurrent client connections to the vhost
	MaxConnections *string `json:"maxConnections,omitempty" tf:"max_connections,omitempty"`

	// Maximum number of queues that can be created on the vhost
	MaxQueues *string `json:"maxQueues,omitempty" tf:"max_queues,omitempty"`

	Tracing *bool `json:"tracing,omitempty" tf:"tracing,omitempty"`
}

type VhostObservation struct {

	// default queue type for new queues
	DefaultQueueType *string `json:"defaultQueueType,omitempty" tf:"default_queue_type,omitempty"`

	// A friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Maximum number of concurrent client connections to the vhost
	MaxConnections *string `json:"maxConnections,omitempty" tf:"max_connections,omitempty"`

	// Maximum number of queues that can be created on the vhost
	MaxQueues *string `json:"maxQueues,omitempty" tf:"max_queues,omitempty"`

	Tracing *bool `json:"tracing,omitempty" tf:"tracing,omitempty"`
}

type VhostParameters struct {

	// default queue type for new queues
	// +kubebuilder:validation:Optional
	DefaultQueueType *string `json:"defaultQueueType,omitempty" tf:"default_queue_type,omitempty"`

	// A friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Maximum number of concurrent client connections to the vhost
	// +kubebuilder:validation:Optional
	MaxConnections *string `json:"maxConnections,omitempty" tf:"max_connections,omitempty"`

	// Maximum number of queues that can be created on the vhost
	// +kubebuilder:validation:Optional
	MaxQueues *string `json:"maxQueues,omitempty" tf:"max_queues,omitempty"`

	// +kubebuilder:validation:Optional
	Tracing *bool `json:"tracing,omitempty" tf:"tracing,omitempty"`
}

// VhostSpec defines the desired state of Vhost
type VhostSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VhostParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VhostInitParameters `json:"initProvider,omitempty"`
}

// VhostStatus defines the observed state of Vhost.
type VhostStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VhostObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Vhost is the Schema for the Vhosts API. Creates and manages a vhost on a RabbitMQ server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rabbitmq}
type Vhost struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VhostSpec   `json:"spec"`
	Status            VhostStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VhostList contains a list of Vhosts
type VhostList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Vhost `json:"items"`
}

// Repository type metadata.
var (
	Vhost_Kind             = "Vhost"
	Vhost_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Vhost_Kind}.String()
	Vhost_KindAPIVersion   = Vhost_Kind + "." + CRDGroupVersion.String()
	Vhost_GroupVersionKind = CRDGroupVersion.WithKind(Vhost_Kind)
)

func init() {
	SchemeBuilder.Register(&Vhost{}, &VhostList{})
}
