-----BEGIN PGP PUBLIC KEY BLOCK-----
iQI2BCABCAAgFiEE4gY7h+3CnxvUR6lEdt4ENCP7XTkFAmT3ROcCHQAACgkQdt4E
NCP7XTmMtBAAkmcDL/H/Bn979JpzyTpUcwtpyy+5o/AtXHNLVTW5/VePhuEB5u+A
dtQdqyZWoUoKWiVKqdeu5H19tQauwgQQpD7lDUuIxp0XJZRCrYEeJrcMws8eSFyF
oqEXxPaohBycJ9DZwU4hYPhk0GQq1DqbJUQUhqMCESoKtQI5lau59gZA7B92/ZPQ
U0HTSx1kT4p7xVpw8N6LSHWuBrWFJziQGo4iXRlGWVPj0D/MGccOpDH+uFYAm9MW
mywUsPf5vviPJDq1zaMb++ko51Fp1E2R8e6EdQM3btLn9d6WIlfQpOE38LY0JDtk
zvM88zCgVyRysvPdwwj0yKA8oAcCP93EQBtUf6oJmc2N3pe1FOEu4ai2xCwHIkGy
6hHKdnStg9clrJS2eSdp1lPyunfkEQNY3Ms43SSlsvUlZ02zmyO+qaEPawfKMdkf
ZVEu4x7v0wXDQLq9z+YNflrP/Go7BVUaT3IYf7oIBVuRdAuXEUBbXZF06syXSHuC
ckXqJIy7VfXn/feITTRiMUpgQo0h7hQOhd15cm0/Tn3gJVE+n8OIh7IWco3iWyXc
CvHfihVbrK8I8Kui5UeRgZJQlPsjMU9WAMzkbBVyhaNikFpGCTcNTXWHW4nm+320
EpT5eBqvrhJy1/zQ4ggb0fPae28jVfiPrkOvUQDH5OKlDKvS0wy+E+c=
=76c+
----END PGP PUBLIC KEY BLOCK-----//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreConfig) DeepCopyInto(out *StoreConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreConfig.
func (in *StoreConfig) DeepCopy() *StoreConfig {
	if in == nil {
		return nil
	}
	out := new(StoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreConfigList) DeepCopyInto(out *StoreConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoreConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreConfigList.
func (in *StoreConfigList) DeepCopy() *StoreConfigList {
	if in == nil {
		return nil
	}
	out := new(StoreConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreConfigSpec) DeepCopyInto(out *StoreConfigSpec) {
	*out = *in
	in.SecretStoreConfig.DeepCopyInto(&out.SecretStoreConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreConfigSpec.
func (in *StoreConfigSpec) DeepCopy() *StoreConfigSpec {
	if in == nil {
		return nil
	}
	out := new(StoreConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreConfigStatus) DeepCopyInto(out *StoreConfigStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreConfigStatus.
func (in *StoreConfigStatus) DeepCopy() *StoreConfigStatus {
	if in == nil {
		return nil
	}
	out := new(StoreConfigStatus)
	in.DeepCopyInto(out)
	return out
}
